version: '3.8'
services:
  postgres-db:
    container_name: postgres-db
    image: postgres:15
    restart: on-failure
    volumes:
      - ./compose-data/postgres-db:/var/lib/pgsql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=${PGDATA}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - postgresql-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  postgresql-net:
    driver: bridge
