FROM gradle:8.5-jdk17 AS builder

WORKDIR /app

COPY . .

RUN gradle clean build -x test  

FROM openjdk:17

WORKDIR /app

COPY --from=builder /app/build/libs/testTask_Effective_Mobile-1.0-SNAPSHOT.jar /app/application.jar

EXPOSE 8080

CMD ["java", "-jar", "application.jar"]
